version: '3'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=firstsql
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./Main.js:/app/Main.js

  db:
    image: mysql:latest
    ports:
      - "3300:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: firstsql
